[package]
name = "pkcs11-rs"
version = "0.0.1"
authors = [ "Sean Burton <seanjburton@gmail.com>" ]
build = "build.rs"

[dependencies]
libloading = "~0.4"
libc = "~0.2"
clippy = "*"
stainless = "^0.1.11"
lazy_static = "~0.2"

[build-dependencies]
bindgen = "^0.25.3"
